name: pull_request_pipeline
on: 
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: provide_branch
        required: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: check_nvm_version
        shell: bash
        run: |
               pwd
               ls -lah
               git branch
               git checkout ${{ github.event.inputs.branch }}
               node -v
               npm -v
      - name: build app 
        uses: actions/setup-node@v4
        with:
          node-version: '20.X'
      - name: check_node version
        run: |
           node -v
           npm -v

      - name: build_clinet_app
        run: |
            echo "-------- clinet build------"
            cd clinet
            npm install
            npm run build
      - name: build_api_app
        run: |
           cd api
           npm install
           npm run build
    
